# -*- coding: utf-8 -*-
"""Простейшая система локализации для GUI LiveSwapping.

Использование:
    import localisation as loc
    text = loc.get("browse")
    loc.set_language("ru")
"""
from __future__ import annotations

from typing import Dict

_LANG = "en"

_TRANSLATIONS: Dict[str, Dict[str, str]] = {
    "en": {
        "language": "Language:",
        "title_video": "LiveSwapping – Video GUI",
        "title_realtime": "LiveSwapping – Realtime GUI",
        "browse": "Browse…",
        "source_image": "Source image:",
        "target_video": "Target video:",
        "target_image": "Target image:",
        "model": "Model (.pth):",
        "resolution": "Resolution:",
        "retain_target_mouth": "Retain target mouth",
        "start": "Start",
        "stop": "Stop",
        "main_params": "Main parameters",
        "advanced_params": "Advanced parameters",
        "options": "Options",
        "attribute_dir": "Attribute direction (.npy):",
        "attribute_steps": "Attribute steps:",
        "delay": "Delay:",
        "send_to_obs": "Send frames to OBS virtual camera",
        "show_fps_delay": "Show FPS and delay",
        "enhance_res_cam": "Enhance webcam resolution to 1920x1080",
        "restart_required": "Please restart GUI to apply language changes.",
        "upscaler": "Upscaler:",
        "up_none": "None",
        "up_gfpgan": "GFPGAN",
        "info_stop": "Press 'q' in the video window or click 'Stop' to exit",
        "provider": "Provider:",
        "provider_cuda": "CUDA (NVIDIA GPU)",
        "provider_directml": "DirectML (AMD/Intel)",
        "provider_openvino": "OpenVINO (Intel)",
        "provider_tensorrt": "TensorRT (Optimized)",
        "provider_cpu": "CPU (Fallback)",
        "provider_info": "Auto-detected based on hardware",
        "input_files": "Input Files",
        "face_swap_model": "Face Swap Model", 
        "face_enhancement": "Face Enhancement (Upscaler)",
        "enable_face_enhancement": "Enable Face Enhancement",
        "processing_settings": "Processing Settings",
        "source_image": "Source Image:",
        "target_video": "Target Video:",
        "target_image": "Target Image:",
        "ai_model": "AI Model:",
        "model_path": "Model Path:",
        "start_processing": "Start Processing",
        "placeholder_source": "Select face image to swap from...",
        "placeholder_target": "Select video to swap faces in...",
        "placeholder_target_image": "Select image to swap faces in...",
        "placeholder_model": "Model will be downloaded automatically...",
        "dialog_select_source": "Select source image",
        "dialog_select_target": "Select target video", 
        "dialog_select_target_image": "Select target image",
        "dialog_select_model": "Select DFM model",
        "filter_images": "Images (*.png *.jpg *.jpeg *.bmp *.tiff)",
        "filter_videos": "Videos (*.mp4 *.avi *.mkv *.mov *.gif *.webm)",
        "filter_models": "DFM Model files (*.onnx *.dfm *.pth)",
        "processing_video": "Processing video... Please wait",
        "processing_image": "Processing image... Please wait",
        "already_running": "Already Running",
        "processing_in_progress": "Processing is already in progress!",
        "missing_source": "Missing Source",
        "missing_target": "Missing Target", 
        "missing_model": "Missing Model",
        "select_valid_source": "Please select a valid source image!",
        "select_valid_target": "Please select a valid target video!",
        "select_valid_target_image": "Please select a valid target image!",
        "select_valid_model": "Please select a valid model!",
        "processing_error": "Processing Error",
        "error_occurred": "An error occurred during processing:",
        "success": "Success!",
        "video_completed": "Video face swapping completed successfully!\n\nOutput saved as: output.mp4",
        "image_completed": "Image face swapping completed successfully!\n\nOutput saved as: output.jpg",
        "stop_processing": "Stop Processing",
        "stop_not_implemented": "Stopping is not yet implemented.\nPlease wait for processing to complete.",
        "process_stopped": "Process stopped!",
        "model_error": "Model Error",
        "failed_to_ensure_model": "Failed to ensure model:",
        "unknown_model_type": "Unknown model type",
        "select_dfm_file": "Select DFM model file (.onnx or .dfm)...",
    },
    "ru": {
        "language": "Язык:",
        "title_video": "LiveSwapping – Видео GUI",
        "title_realtime": "LiveSwapping – Реал-тайм GUI",
        "browse": "Обзор…",
        "source_image": "Исходное изображение:",
        "target_video": "Целевое видео:",
        "target_image": "Целевое изображение:",
        "model": "Модель (.pth):",
        "resolution": "Разрешение:",
        "retain_target_mouth": "Сохранить рот цели",
        "start": "Запустить",
        "stop": "Остановить",
        "main_params": "Основные параметры",
        "advanced_params": "Дополнительные параметры",
        "options": "Опции",
        "attribute_dir": "Направление атрибута (.npy):",
        "attribute_steps": "Шаги атрибута:",
        "delay": "Задержка:",
        "send_to_obs": "Отправлять кадры в OBS виртуальную камеру",
        "show_fps_delay": "Показывать FPS и задержку",
        "enhance_res_cam": "Увеличить разрешение веб-камеры до 1920x1080",
        "restart_required": "Перезапустите GUI для применения изменений языка.",
        "upscaler": "Апскейлер:",
        "up_none": "Без",
        "up_gfpgan": "GFPGAN",
        "info_stop": "Для остановки нажмите 'q' в окне видео или кнопку 'Остановить'",
        "provider": "Провайдер:",
        "provider_cuda": "CUDA (NVIDIA GPU)",
        "provider_directml": "DirectML (AMD/Intel)",
        "provider_openvino": "OpenVINO (Intel)",
        "provider_tensorrt": "TensorRT (Оптимизированный)",
        "provider_cpu": "CPU (Резервный)",
        "provider_info": "Автоопределение по оборудованию",
        "input_files": "Входные файлы",
        "face_swap_model": "Модель замены лица",
        "face_enhancement": "Улучшение лица (Апскейлер)",
        "enable_face_enhancement": "Включить улучшение лица",
        "processing_settings": "Настройки обработки",
        "source_image": "Исходное изображение:",
        "target_video": "Целевое видео:",
        "target_image": "Целевое изображение:",
        "ai_model": "ИИ модель:",
        "model_path": "Путь к модели:",
        "start_processing": "Начать обработку",
        "placeholder_source": "Выберите изображение лица для замены...",
        "placeholder_target": "Выберите видео для замены лиц...",
        "placeholder_target_image": "Выберите изображение для замены лиц...",
        "placeholder_model": "Модель будет загружена автоматически...",
        "dialog_select_source": "Выберите исходное изображение",
        "dialog_select_target": "Выберите целевое видео",
        "dialog_select_target_image": "Выберите целевое изображение",
        "dialog_select_model": "Выберите модель DFM",
        "filter_images": "Изображения (*.png *.jpg *.jpeg *.bmp *.tiff)",
        "filter_videos": "Видео (*.mp4 *.avi *.mkv *.mov *.gif *.webm)",
        "filter_models": "Файлы модели DFM (*.onnx *.dfm *.pth)",
        "processing_video": "Обработка видео... Пожалуйста, подождите",
        "processing_image": "Обработка изображения... Пожалуйста, подождите",
        "already_running": "Уже запущен",
        "processing_in_progress": "Обработка уже выполняется!",
        "missing_source": "Отсутствует источник",
        "missing_target": "Отсутствует цель",
        "missing_model": "Отсутствует модель",
        "select_valid_source": "Пожалуйста, выберите корректное исходное изображение!",
        "select_valid_target": "Пожалуйста, выберите корректное целевое видео!",
        "select_valid_target_image": "Пожалуйста, выберите корректное целевое изображение!",
        "select_valid_model": "Пожалуйста, выберите корректную модель!",
        "processing_error": "Ошибка обработки",
        "error_occurred": "Произошла ошибка во время обработки:",
        "success": "Успешно!",
        "video_completed": "Замена лиц в видео завершена успешно!\n\nВыходной файл сохранен как: output.mp4",
        "image_completed": "Замена лиц в изображении завершена успешно!\n\nВыходной файл сохранен как: output.jpg",
        "stop_processing": "Остановить обработку",
        "stop_not_implemented": "Остановка еще не реализована.\nПожалуйста, дождитесь завершения обработки.",
        "process_stopped": "Процесс остановлен!",
        "model_error": "Ошибка модели",
        "failed_to_ensure_model": "Не удалось обеспечить модель:",
        "unknown_model_type": "Неизвестный тип модели",
        "select_dfm_file": "Выберите файл модели DFM (.onnx или .dfm)...",
    },
}


def set_language(lang: str) -> None:
    """Установить текущий язык ("en" или "ru")."""
    global _LANG
    if lang in _TRANSLATIONS:
        _LANG = lang
    else:
        raise ValueError(f"Unsupported language: {lang}")


def get(key: str) -> str:
    """Получить перевод для заданного ключа."""
    return _TRANSLATIONS.get(_LANG, {}).get(key, _TRANSLATIONS["en"].get(key, key)) 